services:
  - type: web
    name: emosync-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health.html
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://emosync-api.onrender.com
      - key: FRONTEND_URL
        value: http://localhost:5173
      - key: SANCTUM_STATEFUL_DOMAINS
        value: localhost:5173,localhost:3000
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromSecret: DB_HOST_SUPABASE
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        fromSecret: DB_USERNAME_SUPABASE
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD_SUPABASE
