#!/bin/sh
set -e

# Ensure APP_KEY is set
if [ -z "$APP_KEY" ] || [ "$APP_KEY" = "SomeRandomString" ]; then
    php artisan key:generate --force
fi

# Storage link
php artisan storage:link --no-interaction 2>/dev/null || true

# Run migrations on startup (safe for Railway)
php artisan migrate --force --no-interaction || true

# Fix permissions for files generated by the root user during startup (e.g., laravel.log)
chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

exec /usr/bin/supervisord -c /etc/supervisord.conf
