#!/bin/sh
set -e

# Ensure APP_KEY is set
if [ -z "$APP_KEY" ] || [ "$APP_KEY" = "SomeRandomString" ]; then
    php artisan key:generate --force
fi

# Storage link
php artisan storage:link --no-interaction 2>/dev/null || true

# Clear & cache config (ensures stale cached config from repo is not used)
php artisan optimize:clear --no-interaction || true
php artisan config:cache --no-interaction || true

# Run migrations on startup (safe for Railway)
php artisan migrate --force --no-interaction || true

# Seed pemicu data (idempotent, safe to run on every deploy)
php artisan db:seed --class=PemicuSeeder --force --no-interaction || true

# Seed admin user (idempotent — firstOrCreate, safe to run on every deploy)
php artisan db:seed --class=AdminSeeder --force --no-interaction || true

# Fix permissions for files generated by the root user during startup (e.g., laravel.log)
chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

exec /usr/bin/supervisord -c /etc/supervisord.conf
